name       : vcdimager
version    : 2.0.1
release    : 1
source     :
    - https://ftp.gnu.org/gnu/vcdimager/vcdimager-2.0.1.tar.gz : 67515fefb9829d054beae40f3e840309be60cda7d68753cafdd526727758f67a
license    : GPL-2.0
component  : multimedia.video
summary    : (Super)Video CD image mastering and ripping tool
description: |
    GNU VCDImager is a full-featured mastering suite for authoring, disassembling and analyzing Video CDs and Super Video CDss.
builddeps  :
    - pkgconfig(libcdio)
    - pkgconfig(popt)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
